-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgbBgB0m0sFIGAi3AU
PrzIidOqOqaNzSfy2fw3evb6gqWgCgYIKoZIzj0DAQehRANCAARbUL09zz1D54Ia
+s/aKu+Vk+YnMkb2DecejbAxcDea2DVJnn5aBz14ufCa2VpKEyF+cE7Pw0BehDv8
iUeOTSb+
-----END PRIVATE KEY-----